import './globals.css'
import { SessionProvider } from 'next-auth/react'
export const metadata = {
  title: 'Hotel Software',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode,
  session: any
}) {
  return (
    <html lang="en">
      <body className={`bg-white-800`}>
        {children}
      </body>
    </html>
  )
}
