import './globals.css'
import { Providers } from './providers'
export const metadata = {
  title: 'Hotel Software',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode,
  session: any
}) {
  return (
    <html lang="en">
      <head>
        <link href="/style/styles.css" rel="stylesheet"/>
      </head>
      <body className={`bg-white-800`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
